name: "Fork Sync"
on:
  schedule:
    - cron:  '0 */2 * * *'
  workflow_dispatch:
jobs:
  sync-master:
    runs-on: ubuntu-latest
    name: "Sync from masterbassist/hello-world@master"
    steps:
    - name: "Checkout: master"
      uses: actions/checkout@v3
      with:
        ref: master
        token: ${{ github.token }}
    - name: "Update: master"
      id: sync-master
      uses: masterbassist/Fork-Sync-With-Upstream-action@fork-sync
      with:
        domain: 'github.com'
        upstream_repository: masterbassist/hello-world
        upstream_branch: master
        target_branch: master
        git_pull_args: --ff-only
        # git_push_args: --force
    - name: Timestamp
      run: date
