---
on:
  schedule:
    - cron: '12 * * * *'

jobs:
  timed_execution:
    runs-on: ubuntu-latest
    steps:
      - name: Not on Monday or Wednesday
        if: github.event.schedule != '12 5 * * *'
        run: echo "This step will be skipped at 5:12 AM"
      - name: Every time
        run: echo "Ran at 12 minutes after the hour"
