on:
  push:
jobs:
  run_on_all_pushes:
    runs-on: ubuntu-latest
    steps:
       - name: "Push notification"
         env:
          BRANCH: ${GITHUB_REF##*/}
          PR: ${{ github.event.pull_request.html_url }}
          UL: ${{ github.event.pull_request.user.login }}
         run: |
          echo "($BRANCH) Pushed by $UL - $PR"
