on:
  push:
jobs:
  run_on_all_pushes:
    runs-on: ubuntu-latest
    steps:
       - name: "Push notification"
         env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR: ${{ github.event.pull_request.html_url }}
          UL: ${{ github.event.pull_request.user.login }}
         run: |
          echo "($GITHUB_TOKEN) Pushed by $UL - $PR"
